use_frameworks!

target 'FidzupSdk_Example' do
  pod 'FidzupSdk', :path => '../'

  target 'FidzupSdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
